### ISSUE TITLE
Simple nextflow example?

### ISSUE THREAD

**Issue by janzheng** [hgbrian/biomodals#1]
This is so cool, and makes it possible for citizen scientists to run their own bioinformatics (without access to clusters!)

Could you show a couple of examples of running a vanilla hello world Nextflow pipelines?

**Comment by hgbrian** [comment]
Hey Jan,
I don't use nextflow so i'd have to think about this.
Part of the reason I like modal is to avoid the extra dependency of workflow managers!

There are two ways it could work:
- modal run a python script that calls nextflow (all nextflow steps in one container)
This is just e.g., run("nextflow run minimap2.nf") in a modal function

- replace the shell commands in nextflow with modal run...
This is just e.g., replacing "minimap2 a.fna b.fna" with "modal run modal_minimap2.py a.fna b.fna" in minimap2.nf
(plus making sure the files appear in the right place.)

I think either could make sense but it depends on what the goal is I guess?

**Comment by hgbrian** [comment]
Hey Jan,
I added `modal_nextflow_example.py` at last.

Hope that helps!

**Comment by janzheng** [comment]
very cool, thank you so much!!!
