### ISSUE TITLE
Boltz not working

### ISSUE THREAD

**Issue by greenrace66** [hgbrian/biomodals#4]
What to do ? @hgbrian 
![Screenshot (65)](https://github.com/user-attachments/assets/1e0a094e-b1d3-461d-ab7a-6c3181c70c1e)

**Comment by hgbrian** [comment]
Pretty sure this is a malformed fasta file.

Check for empty lines at the end of the file. 

I removed some of the fasta processing so now you should just prepare your fasta as Boltz recommends.
